# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa85094bab54c35a20dd4797387bd6f2942fae5764f43f2b771f1ff13ab6a70e3d4ba3d831fd7fa36f34e184c8a175d653892a9f5b63c9ccf09936dde46614fd

test:
  secret_key_base: 917dd1f2ef83635cf0aa0f473b2453ffe6005e053636c8373637e8f2fce6eb1c79c336534d04386430bb9f1033644812cc1ba7c5385948ab255cecdfc13523bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
